import { Injectable } from '@angular/core';
import 'rxjs/add/operator/map';

@Injectable()
export class TipsModel {

  aklTips = [
    {"status":"open",
      "rated_title":"Auckland","tip_id":"754","date":"1399503000","tip_creator":"55","rating":"7","img":"","desc":"Take a 30 minute flight from Auckland Airport or Dairy Flat and head to Great Barrier Island.  Its like flying into a scene from Jurassic Park.  Totally unspoilt beauty, pristine beaches.  Take a walk to one of the waterfalls on the island or the hot springs for a dip.  Bliss","mod":"0","type":"region","related_id":"26",
      "u":{"f":"Barbara","l":"Murphy","i":"//tiki.grabaseat.co.nz/u/a/55.jpg","id":"55","cm":"0"},"up":"5","down":"2","rated_value":"","user_rated":"no"},
    {"status":"open","rated_title":"Auckland","tip_id":"842","date":"1400442960","tip_creator":"119","rating":"1","img":"","desc":"30mins from the CBD is the Clevedon Farmers Market.  It runs every Sunday from 8.30am - 12pm.  Take the family, the dog, or pet goat (seriously) and enjoy a hot coffee while buying fresh fruit and produce, tasty baking, breads, cheeses, preserves and even flowers.  It is located in a rural setting, and is everything a farmers market should be.","mod":"0","type":"region","related_id":"26",
      "u":{"f":"Erika","l":"Rogers","i":"//tiki.grabaseat.co.nz/u/a/119.jpg","id":"119","cm":"0"},"up":"1","down":"0","rated_value":"","user_rated":"no"},
    {"status":"open","rated_title":"Auckland","tip_id":"848","date":"1400444220","tip_creator":"149","rating":"1","img":"","desc":"Fish and chips at sunset on Mt Victoria, Devonport - best views of the city and islands. You can feel like you are the only people up there and its so peaceful. Only a 5 minute walk from Devonport village, where you can pick up your fish and chips!","mod":"0","type":"region","related_id":"26",
      "u":{"f":"Samara","l":"Cottam","i":"//tiki.grabaseat.co.nz/u/a/149.jpg","id":"149","cm":"0"},"up":"1","down":"0","rated_value":"","user_rated":"no"},
    {"status":"open","rated_title":"Auckland","tip_id":"1387","date":"1401402840","tip_creator":"50","rating":"","img":"","desc":"If you're up in Auckland over the weekend, check out where the local night markets are on. We always go to the Onehunga ones (in the dressmart carpark) on a Thursday night. Really good dumplings, and desserts. And a good chance to hang out with the locals!","mod":"0","type":"region","related_id":"26",
      "u":{"f":"Verity","l":"Dookia","i":"//tiki.grabaseat.co.nz/u/a/50.jpg","id":"50","cm":"31"},"up":"0","down":"0","rated_value":"","user_rated":"no"},
    {"status":"open","rated_title":"Auckland","tip_id":"1404","date":"1401418620","tip_creator":"1048","rating":"","img":"","desc":"Enjoy the beautiful views from on top of One Tree Hill. Another fantastic spot is North Head. Great for picnics or just the view. My boys enjoyed sliding down the grass. Take a torch and explore the tunnels.","mod":"0","type":"region","related_id":"26",
      "u":{"f":"Melinda","l":"Anderson","i":"//tiki.grabaseat.co.nz/u/a/1048.jpg","id":"1048","cm":"0"},"up":"0","down":"0","rated_value":"","user_rated":"no"},
    {"status":"open","rated_title":"Auckland","tip_id":"1255","date":"1401176820","tip_creator":"799","rating":"","img":"","desc":"Awhitu Lighthouse- 40 or so ks from stunning Waiuku, atmospheric and stunning. , Then on to the reserve up the road to view the Manukau harbour from  the other side. ","mod":"0","type":"region","related_id":"26",
      "u":{"f":"Diane","l":"Thomson","i":"//tiki.grabaseat.co.nz/u/a/799.jpg","id":"799","cm":"0"},"up":"0","down":"0","rated_value":"","user_rated":"no"},
    {"status":"open","rated_title":"Auckland","tip_id":"762","date":"1399594440","tip_creator":"56","rating":"-1.0000","img":"","desc":"Walk from Milford to Takapuna along the beach walk. You will walk through secluded bays, climb rocks, play on the 'Giants' chair and see all sorts of wildlife. If you are lucky you will see a Penguin.nnWhen you reach Takapuna, ensure you have lunch at the Takapuna Cafe which is right at the end of the walk. Amazing cakes and coffees. ","mod":"0","type":"region","related_id":"26",
      "u":{"f":"Simon","l":"Court","i":"//tiki.grabaseat.co.nz/u/a/56.jpg","id":"56","cm":"0"},"up":"0","down":"1","rated_value":"","user_rated":"no"},
    {"status":"open","rated_title":"Auckland","tip_id":"1309","date":"1401224040","tip_creator":"901","rating":"","img":"","desc":"Why not do the coast to coast walk. It is a 16km walk taking you through amazing landscapes and historic sites.  You can either start at the Viaduct Harbour walking through to Onehunga, Manukau Harbour, or the other way around.  Its a great way of seeing Auckland without any cost, unless you want to stop for coffee along the way. Totally enjoyable.","mod":"0","type":"region","related_id":"26",
      "u":{"f":"Bronwyn","l":"Malcolm","i":"//tiki.grabaseat.co.nz/u/a/901.jpg","id":"901","cm":"0"},"up":"0","down":"0","rated_value":"","user_rated":"no"},{"status":"open","rated_title":"Auckland","tip_id":"1209","date":"1401084480","tip_creator":"90","rating":"","img":"","desc":"Be sure to drop by Jack Tars for a relaxing evening with friends and booze. Also, the view of the harbor is amazing.","mod":"0","type":"region","related_id":"26","u":{"f":"Mithun","l":"Chakravarthy","i":"//tiki.grabaseat.co.nz/u/a/90.jpg","id":"90","cm":"0"},"up":"0","down":"0","rated_value":"","user_rated":"no"},
    {"status":"open","rated_title":"Auckland","tip_id":"1388","date":"1401402960","tip_creator":"50","rating":"","img":"","desc":"You've got to go out to Piha. You'll recognise it from Piha... it's one of the best beaches to visit in winter because of its striking beauty. On the way there, stop in at the Refreshment Room. Amazing restaurant for dinner or lunch. The fries are a must.. and their pasta is handmade and buonissimo!!!","mod":"0","type":"region","related_id":"26","u":{"f":"Verity","l":"Dookia","i":"//tiki.grabaseat.co.nz/u/a/50.jpg","id":"50","cm":"31"},"up":"0","down":"0","rated_value":"","user_rated":"no"},
    {"status":"open","rated_title":"Auckland","tip_id":"1160","date":"1400789460","tip_creator":"633","rating":"","img":"","desc":"Visit Waiheke 35 minutes by ferry beautiful white sandy beaches, great cafes go on a wine trail. Bush walks fantastic scanery. Peace and friendly people what more do you want ","mod":"0","type":"region","related_id":"26","u":{"f":"Betty","l":"McGregor","i":"//tiki.grabaseat.co.nz/u/a/633.jpg","id":"633","cm":"0"},"up":"0","down":"0","rated_value":"","user_rated":"no"},
    {"status":"open","rated_title":"Auckland","tip_id":"1423","date":"1401424740","tip_creator":"50","rating":"","img":"","desc":"If you haven't been to Auckland in a while, you have to go and check out Britomart. All the development means there's heaps of shops and restaurants to try out. Great day or night. There's always a new restaurant popping up... Ortolana is the best & awesome for dessert.","mod":"0","type":"region","related_id":"26","u":{"f":"Verity","l":"Dookia","i":"//tiki.grabaseat.co.nz/u/a/50.jpg","id":"50","cm":"31"},"up":"0","down":"0","rated_value":"","user_rated":"no"}
  ];

  constructor() {
  }

}
